let cheerio = require('cheerio')

process.stdin.resume()
process.stdin.setEncoding('utf8')

let html = ''
let emoji = []

process.stdin.on('data', function(chunk) { html += chunk })
process.stdin.on('end', function() {
  const $ = cheerio.load(html)

  // polyfill :simple_smile:
  emoji.push("':simple_smile:': emojione.shortnameToImage(':smile:')")

  // custom emojis
  $('.emoji_row').each(function() {
    const $elem = $(this)
    const name = $elem.find('[headers="custom_emoji_name"]').text().trim()
    const path = $elem.find('[headers="custom_emoji_image"] > span').data('original').replace(/^https?:/, '')

    emoji.push(`'${name}': '<img class="emojione" alt="${name}" src="${path}" />'`)
  })

  console.log(
`// This file is generated by \`utils/emoji-updater\`
//
// Please copy the source from https://g0v-tw.slack.com/customize/emoji
// and run \`npm start\` under \`utils/emoji-updater\` folder to generate it.
//
// Just paste the source may hang your console.
(function(emojione) {
  var aliases, exp, emoji;

  emojione.ascii = true;

  // custom emojis
  aliases = {
    ${ emoji.join(',\n    ') }
  };

  exp = /\\:\\S+\\:(?!")/g;
  emoji = function(msg) {
    var m, result, alias;

    m = emojione.toImage(msg);

    while (result = exp.exec(m)) {
      result = result[0];
      alias = aliases[result] || result;
      m = m.replace(result, alias);
    }

    return m;
  }

  window.emoji = emoji;
}(emojione));`
  )
})
